services:
  accountdb:
    extends:
      file: common-config.yml
      service: db-base-config
    container_name: accountdb
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=accountdb

  loansdb:
    extends:
      file: common-config.yml
      service: db-base-config
    container_name: loansdb
    ports:
      - "3308:3306"
    environment:
      - MYSQL_DATABASE=loansdb

  cardsdb:
    extends:
      file: common-config.yml
      service: db-base-config
    container_name: cardsdb
    ports:
      - "3309:3306"
    environment:
      - MYSQL_DATABASE=cardsdb


  rabbit:
    image: rabbitmq:latest
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
    extends:
      file: common-config.yml
      service: network-deploy-service

  configserver:
    image: hichamazeroual2002/configserver:s9
    container_name: configserver
    ports:
      - "8071:8071"
    depends_on:
      rabbit:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --silent http://localhost:8071/actuator/health/readiness | grep -q '\"status\":\"UP\"' || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 60s
    extends:
      file: common-config.yml
      service: microservice-base-config

  eurekaserver:
    image: hichamazeroual2002/eurekaserver:s9
    container_name: eurekaserver
    ports:
      - "8070:8070"
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --silent http://localhost:8070/actuator/health/readiness | grep -q '\"status\":\"UP\"' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 120s
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "eurekaserver"
    extends:
      file: common-config.yml
      service: microservice-configserver-config


  accounts:
    image: hichamazeroual2002/accounts:s9
    container_name: accounts
    ports:
      - "8080:8080"
    depends_on:
      accountdb:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail --silent http://localhost:8080/actuator/health/readiness | grep -q '\"status\":\"UP\"' || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 120s
    environment:
      SPRING_APPLICATION_NAME: "accounts"
      SPRING_DATASOURCE_URL: "jdbc:mysql://accountdb:3306/accountdb"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  loans:
    image: hichamazeroual2002/loans:s9
    container_name: loans
    ports:
      - "8090:8090"
    depends_on:
      loansdb:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail --silent http://localhost:8090/actuator/health/readiness | grep -q '\"status\":\"UP\"' || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 120s
    environment:
      SPRING_APPLICATION_NAME: "loans"
      SPRING_DATASOURCE_URL: "jdbc:mysql://loansdb:3306/loansdb"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  cards:
    image: hichamazeroual2002/cards:s9
    container_name: cards
    ports:
      - "9000:9000"
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail --silent http://localhost:9000/actuator/health/readiness | grep -q '\"status\":\"UP\"' || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 120s
    depends_on:
      cardsdb:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "cards"
      SPRING_DATASOURCE_URL: "jdbc:mysql://cardsdb:3306/cardsdb"
    extends:
      file: common-config.yml
      service: microservice-eureka-config


  gatewayserver:
    image: hichamazeroual2002/gatwayserver:s9
    container_name: gatwayserver
    ports:
      - "8072:8072"
    depends_on:
      accounts:
        condition: service_healthy
      cards:
        condition: service_healthy
      loans:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "gatwayserver"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

networks:
  bank-network:
    driver: bridge