apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts-deployment
  labels:
    app: accounts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accounts
  template:
    metadata:
      labels:
        app: accounts
    spec:
      containers:
        - name: accounts
          image: hichamazeroual2002/accounts:s11  # Assuming your Docker image name
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: eazybank-configmap