apiVersion: apps/v1
kind: Deployment
metadata:
  name: configserver-deployment
  labels:
    app: configserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configserver
  template:
    metadata:
      labels:
        app: configserver
    spec:
      containers:
        - name: configserver
          image: hichamazeroual2002/configserver:s11  # Assuming your Docker image name
          ports:
            - containerPort: 8071
          envFrom:
            - configMapRef:
                name: eazybank-configmap