apiVersion: apps/v1
kind: Deployment
metadata:
  name: loans-deployment
  labels:
    app: loans
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loans
  template:
    metadata:
      labels:
        app: loans
    spec:
      containers:
        - name: loans
          image: hichamazeroual2002/loans:s11  # Assuming your Docker image name
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: eazybank-configmap